image: ${CI_REGISTRY_IMAGE}

stages:
  - test

doxec_unittest:
  stage: test
  script:
    - python3 -m unittest -v doxec.tests

     
doxec_doctest:
  stage: test
  script:
    - python3 -m doctest doxec/*.py

README:
    stage: test
    variables:
      DOXEC_COLOR: 0

    script:
     - bin/doxec --color README.md 

